apiVersion: v1
kind: Service
metadata:
  # Name of the service
  name: stephen-app-service
  labels:
    app: stephen-app

spec:
  # LoadBalancer type tells AWS to provision an ALB automatically
  type: LoadBalancer

  # Route traffic to pods with this label
  selector:
    app: stephen-app

  ports:
    - name: http
      # Port the load balancer listens on
      port: 80
      # Port the container is running on
      targetPort: 80
      protocol: TCP
